import { Box, Text } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import { Banner } from "../components/banner/Banner";
import { BlueBlock } from "../components/blueBlock/BlueBlock";
import { InputBlock } from "../components/inputblock/InputBlock";
import { MyTabs } from "../components/Tabs/MyTabs";

const Home: NextPage = () => {
  return (
    <Box>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Banner />
        <BlueBlock />
        <MyTabs />
      </Box>
    </Box>
  );
};

export default Home;
